export const experiences = [
  {
    title: "Senior Full Stack Engineer",
    imgSource: "company-logos/LivaNovalogolarge.jpg",
    year: "June 2022 - Present",
    category: "Remote",
    description: [
      "VNS Therapy Ecosystem",
      "• Developed a cross-platform solution for managing Vagus Nerve Stimulation (VNS) therapy in patients with drug-resistant epilepsy",
      "• Built a .NET MAUI Android app for clinicians to simulate and manage therapy",
      "• Integrated BLE/COM protocols for device communication with implantable medical devices",
      "• Designed a clinician-facing React web portal (Epsy Hub) for tracking therapy and managing patients",
      "• Implemented AWS-based backend with Cognito, GraphQL, DynamoDB, and Terraform for secure, scalable deployment",
      "• Automated CI/CD pipelines and device deployments using Azure DevOps and Samsung Knox.",
    ],
  },
  {
    title: "Deloitte Consulting LLC",
    imgSource: "company-logos/Deloitte_Logo.jpg",
    year: "April 2019 - June 2022",
    category: "Gilbert, AZ",
    description: [
      "Internal Xamarin App & State Health Platform",
      "• Built a Xamarin.Forms communication app for Deloitte leaders to manage meetings and secure document sharing.",
      "• Integrated Microsoft Graph API for authentication and PDF stream decryption.",
      "• Developed cloud-native Medicaid analytics/reporting platform using React, FusionJS, and Figma mockups.",
      "• Engineered AWS-hosted microservices in Node.js with RESTful API design and MVVM architecture.",
      "• Optimized PostgreSQL and Redshift schemas for financial reporting workflows.",
      "• Deployed Docker-based services with multi-instance load balancing on AWS.",
    ],
  },
  {
    title: "Siemens Industry Inc",
    imgSource: "company-logos/logo-siemens.png",
    year: "Oct 2018 - Mar 2019",
    category: "Grand Prairie, TX",
    description: [
      "SmartGear Mobile App",
      "• Developed a cross-platform mobile app for Android and iOS to monitor SmartGear® switchgear devices using Xamarin.Forms and MVVM.",
      "• Enabled real-time diagnostics and alerts with Socket.IO and JSON polling.",
      "• Integrated WPA2 MODBUS for secure local device communication.",
      "• Implemented biometric authentication and push notifications using AWS SNS.",
      "• Visualized live electrical data and alarms using Syncfusion (charts, custom pages, 3D graphics).",
      "• Bound live LVS data (breaker status, meter readings) using data-binding and MVVM architecture.",
    ],
  },
  {
    title: "National Life Group",
    imgSource: "company-logos/NLG_White_Logo_2x_Green.png",
    year: "Sept 2019 - Sept 2018",
    category: "Montpelier, VT",
    description: [
      "Customer App Development",
      "• Developed and published the company’s first cross-platform mobile app using Xamarin.Forms.",
      "• Implemented secure authentication with OAuth and multi-factor authentication (MFA).",
      "• Integrated SQLite for local data storage and SkiaSharp for dynamic chart rendering.",
      "• Ensured accessibility through automation properties and text-to-speech (TTS) compatibility.",
    ],
  },
  {
    title: "Toyota Motor North America, Inc",
    imgSource: "company-logos/Toyota-Logo-2010-2019.png",
    year: "2019",
    category: "Torrance, CA",
    description: [
      "Lexus Drivers Mobile App",
      "• Delivered the Lexus Drivers App for Android and iOS using Xamarin.Forms.",
      "• Implemented VIN barcode scanning, push notifications, and local storage with SQLite.",
      "• Integrated analytics tracking and Google Maps for enhanced user experience.",
      "• Followed MVVM architecture and used HockeyApp for app distribution and crash reporting.",
    ],
  },
];

export const skills = [
  { name: "Javascript", icon: "logos/javascript-original.svg" },
  { name: "Typescript", icon: "logos/typescript-original.svg" },
  { name: "Java", icon: "logos/java-original.svg" },
  { name: "C#", icon: "logos/csharp-original.svg" },
  { name: "React", icon: "logos/react-original.svg" },
  { name: "Angular", icon: "logos/angularjs-original.svg" },
  { name: "TailWindcss", icon: "logos/tailwindcss-original.svg" },
  { name: "Sass/Scss", icon: "logos/sass-original.svg" },
  { name: "Node.js", icon: "logos/nodejs-original-wordmark.svg" },
  { name: "GraphQL", icon: "logos/graphql-plain.svg" },
  { name: "Socket.IO", icon: "logos/socketio-original.svg" },
  { name: "PostgreSQL", icon: "logos/postgresql-original.svg" },
  { name: "SQLite", icon: "logos/sqlite-original.svg" },
  { name: "MongoDB", icon: "logos/mongodb-original.svg" },
  { name: "Figma", icon: "logos/figma-original.svg" },
  { name: "Git", icon: "logos/github-original.svg" },
  { name: "Docker", icon: "logos/docker-original.svg" },
  { name: "Azure DevOps", icon: "logos/azuredevops-original.svg" },
  {
    name: "AWS Services",
    icon: "logos/amazonwebservices-original-wordmark.svg",
  },
  { name: "Xamarin", icon: "logos/xamarin-original.svg" },
  { name: ".Net", icon: "logos/dot-net-plain-wordmark.svg" },
  { name: "Android", icon: "logos/android-original.svg" },
  { name: "IOS", icon: "logos/apple-original.svg" },
];

export const works = [
  {
    title: "Epsy Portal",
    description:
      "A health companion app for epilepsy patients to log seizures, manage medications, and share insights with clinicians via the connected Epsy Hub portal.",
    image: "work-logos/epsy_portal.png",
    link: "https://www.epsyhealth.com/",
    tags: [
      "React",
      "Typescript",
      "Tailwindcss",
      "Material UI",
      "Redux Toolkit",
      "React Query",
      "PostgreSQL",
      "GraphQL",
      "Python",
      "Terraform",
      "AWS Amplify",
    ],
  },
  {
    title: "Sm@rtGear Mobile App",
    description:
      "An industrial mobile solution providing real-time diagnostics and control for SmartGear switchgear systems, enhancing electrical safety and equipment monitoring.",
    image: "work-logos/Siemens_app.png",
    link: "https://www.siemens.com/us/en/products/energy/low-voltage/smart-technology/smart-mobile.html",
    tags: [
      "Xamarin.Forms",
      "Node.js",
      "Socket.IO",
      "REST API",
      "JavaScript",
      "SQLite",
      "Modbus Server",
      "MVVM",
      "Syncfusion",
      "AWS",
    ],
  },
  {
    title: "National Life Group App",
    description:
      "A cross-platform mobile app enabling policyholders to manage life insurance and annuity accounts, make payments, view balances, and contact agents securely.",
    image: "work-logos/customer-hd-lg.jpg",
    link: "https://www.nationallife.com/customertools",
    tags: [
      "Xamarin.Forms",
      "REST API",
      "ASP.Net",
      "SkiaSharp",
      "SQLite",
      "MVVM",
      "Syncfusion",
    ],
  },
  {
    title: "Lexus Drivers App",
    description:
      "A companion app for Lexus owners offering service history, remote vehicle access, maintenance alerts, and VIN-based features for a seamless ownership experience.",
    image: "work-logos/Lexus_drivers.png",
    link: "https://www.lexus.com/My-Lexus/resources/connected-technology",
    tags: [
      "Xamarin.Forms",
      "REST API",
      "ASP.Net",
      "SQLite",
      "MVVM",
      "Syncfusion",
    ],
  },
];
